source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'
gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'
gem 'uglifier', '>= 1.0.3'
gem 'jquery-rails'
gem 'devise', '~> 3.4.0'
gem 'paperclip', '~> 4.2.0'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'searchkick'
